name: Deploy Next.js Frontend to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Deploy to Oracle Cloud Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -e
          
          echo "=== Starting Frontend Deployment ==="
          
          cd ~/prj-sketch-frontend
          git pull origin main
          
          # .env.local 파일 생성
          cat > .env.local << 'ENVEOF'
          NEXT_PUBLIC_API_URL=http://${{ secrets.SERVER_IP }}:8000
          ENVEOF
          
          # 의존성 설치
          echo "=== Installing Dependencies ==="
          npm install
          
          # 빌드
          echo "=== Building Next.js ==="
          npm run build
          
          # 기존 서버 종료
          echo "=== Stopping Existing Next.js Server ==="
          screen -S nextjs -X quit || true
          
          sleep 3
          
          # 새 서버 시작
          echo "=== Starting Next.js Server ==="
          screen -dmS nextjs bash -c 'cd ~/prj-sketch-frontend && npm start > nextjs.log 2>&1'
          
          sleep 5
          
          # 서버 확인
          if screen -list | grep -q "nextjs"; then
            echo "Next.js server is running"
          else
            echo "Failed to start Next.js server"
            exit 1
          fi
          
          tail -n 20 nextjs.log
          
          echo "=== Frontend Deployment Completed ==="